In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [12]:
# df = pd.read_csv("C:/Office 2019/NLP/Fake_News_Detection_System/Dataset/news_dataset.csv")
# df

In [13]:
df = pd.read_csv("C:/Office 2019/NLP/Fake_News_Detection_System/Dataset/dataset.csv")

df1 = pd.DataFrame({'text':df['Real News'],"label":"REAL"})
df2 = pd.DataFrame({'text':df['Fake News'],"label":"FAKE"})
df3 = pd.DataFrame({'text':df['AI-generated Fake News'],"label":"FAKE"})

df = pd.concat([df1,df2,df3],ignore_index=True,)
df

                                                  text label
0    The head of a conservative Republican faction ...  REAL
1    Transgender people will be allowed for the fir...  REAL
2    The special counsel investigation of links bet...  REAL
3    Trump campaign adviser George Papadopoulos tol...  REAL
4    SEATTLE/President Donald Trump called on the U...  REAL
..                                                 ...   ...
892  In a disturbing new revelation, former Preside...  FAKE
893  New Mexico is drawing national attention after...  FAKE
894  n a recent statement that has stirred up both ...  FAKE
895  In a growing wave of controversy sweeping acro...  FAKE
896  In a tense moment during today’s White House b...  FAKE

[897 rows x 2 columns]

In [14]:
df['text'] = df['text'].apply(lambda x: str(x).lower())
df

                                                  text label
0    the head of a conservative republican faction ...  REAL
1    transgender people will be allowed for the fir...  REAL
2    the special counsel investigation of links bet...  REAL
3    trump campaign adviser george papadopoulos tol...  REAL
4    seattle/president donald trump called on the u...  REAL
..                                                 ...   ...
892  in a disturbing new revelation, former preside...  FAKE
893  new mexico is drawing national attention after...  FAKE
894  n a recent statement that has stirred up both ...  FAKE
895  in a growing wave of controversy sweeping acro...  FAKE
896  in a tense moment during today’s white house b...  FAKE

[897 rows x 2 columns]

In [15]:
import string
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ajeet\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ajeet\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ajeet\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [16]:
def remove_putch_stopword_number(txt):
    txt = re.sub(r'\d+','',txt)
    txt = re.sub(r'["“”\'‘’]', '', txt)
    words = word_tokenize(txt)

    stop_words = set(stopwords.words('english'))
    clean_words = [word for word in words if word not in string.punctuation and word not in stop_words and not word.isdigit()]

    return ' '.join(clean_words)

df["text"] = df["text"].apply(remove_putch_stopword_number)

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'],df['label'], test_size=0.33, random_state=42)

In [18]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
# 1 -> True and 0 -> False

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [20]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(max_iter=10000)
log_model.fit(X_train,y_train)

LogisticRegression(max_iter=10000)

In [21]:
from sklearn.metrics import accuracy_score
log_pred = log_model.predict(X_test)
accuracy_score(y_test,log_pred)

0.9494949494949495

In [22]:
log_model.predict_proba(X_test)

array([[0.75721554, 0.24278446],
       [0.87366167, 0.12633833],
       [0.76881591, 0.23118409],
       [0.73577616, 0.26422384],
       [0.33445356, 0.66554644],
       [0.8588591 , 0.1411409 ],
       [0.76848036, 0.23151964],
       [0.73732648, 0.26267352],
       [0.37209524, 0.62790476],
       [0.46486401, 0.53513599],
       [0.41434845, 0.58565155],
       [0.38912308, 0.61087692],
       [0.83938494, 0.16061506],
       [0.35849029, 0.64150971],
       [0.82805925, 0.17194075],
       [0.74247986, 0.25752014],
       [0.68606497, 0.31393503],
       [0.90233276, 0.09766724],
       [0.85364597, 0.14635403],
       [0.14979177, 0.85020823],
       [0.78681046, 0.21318954],
       [0.82977382, 0.17022618],
       [0.40811362, 0.59188638],
       [0.87337283, 0.12662717],
       [0.81773946, 0.18226054],
       [0.79634356, 0.20365644],
       [0.35592382, 0.64407618],
       [0.86142419, 0.13857581],
       [0.36903912, 0.63096088],
       [0.92825702, 0.07174298],
       [0.66080798, 0.33919202],
       [0.28729423, 0.71270577],
       [0.43325857, 0.56674143],
       [0.72759458, 0.27240542],
       [0.2011296 , 0.7988704 ],
       [0.91258737, 0.08741263],
       [0.29727053, 0.70272947],
       [0.41801385, 0.58198615],
       [0.41687368, 0.58312632],
       [0.87609884, 0.12390116],
       [0.23367384, 0.76632616],
       [0.83926789, 0.16073211],
       [0.86670933, 0.13329067],
       [0.81976735, 0.18023265],
       [0.78915974, 0.21084026],
       [0.26527179, 0.73472821],
       [0.37022274, 0.62977726],
       [0.79170221, 0.20829779],
       [0.40485881, 0.59514119],
       [0.85173884, 0.14826116],
       [0.83220364, 0.16779636],
       [0.79658581, 0.20341419],
       [0.77859907, 0.22140093],
       [0.90769278, 0.09230722],
       [0.29029991, 0.70970009],
       [0.85255276, 0.14744724],
       [0.20989088, 0.79010912],
       [0.6629043 , 0.3370957 ],
       [0.370758  , 0.629242  ],
       [0.32825493, 0.67174507],
       [0.76806676, 0.23193324],
       [0.79969881, 0.20030119],
       [0.85957808, 0.14042192],
       [0.14624909, 0.85375091],
       [0.15917354, 0.84082646],
       [0.76628794, 0.23371206],
       [0.45598824, 0.54401176],
       [0.28766825, 0.71233175],
       [0.64890361, 0.35109639],
       [0.81393439, 0.18606561],
       [0.73584895, 0.26415105],
       [0.8004676 , 0.1995324 ],
       [0.90545725, 0.09454275],
       [0.76113926, 0.23886074],
       [0.86249007, 0.13750993],
       [0.87272231, 0.12727769],
       [0.54575893, 0.45424107],
       [0.78785174, 0.21214826],
       [0.93292454, 0.06707546],
       [0.89113664, 0.10886336],
       [0.65529824, 0.34470176],
       [0.51208429, 0.48791571],
       [0.82856804, 0.17143196],
       [0.83118309, 0.16881691],
       [0.67318054, 0.32681946],
       [0.82047801, 0.17952199],
       [0.48066929, 0.51933071],
       [0.83206779, 0.16793221],
       [0.8771806 , 0.1228194 ],
       [0.53461812, 0.46538188],
       [0.08447116, 0.91552884],
       [0.92128704, 0.07871296],
       [0.88086988, 0.11913012],
       [0.78340404, 0.21659596],
       [0.21579953, 0.78420047],
       [0.17592234, 0.82407766],
       [0.46232652, 0.53767348],
       [0.19101029, 0.80898971],
       [0.45134186, 0.54865814],
       [0.82340762, 0.17659238],
       [0.8626293 , 0.1373707 ],
       [0.84545882, 0.15454118],
       [0.27124757, 0.72875243],
       [0.93136047, 0.06863953],
       [0.88607749, 0.11392251],
       [0.46395284, 0.53604716],
       [0.78078288, 0.21921712],
       [0.86667883, 0.13332117],
       [0.84231334, 0.15768666],
       [0.58292157, 0.41707843],
       [0.66652539, 0.33347461],
       [0.07974319, 0.92025681],
       [0.65308808, 0.34691192],
       [0.79660746, 0.20339254],
       [0.7781681 , 0.2218319 ],
       [0.92228348, 0.07771652],
       [0.63343827, 0.36656173],
       [0.93841856, 0.06158144],
       [0.81906023, 0.18093977],
       [0.79681041, 0.20318959],
       [0.77421204, 0.22578796],
       [0.68838559, 0.31161441],
       [0.79873628, 0.20126372],
       [0.31970207, 0.68029793],
       [0.83477501, 0.16522499],
       [0.76161666, 0.23838334],
       [0.88580685, 0.11419315],
       [0.07179691, 0.92820309],
       [0.64081859, 0.35918141],
       [0.87114997, 0.12885003],
       [0.77441345, 0.22558655],
       [0.40128413, 0.59871587],
       [0.76874868, 0.23125132],
       [0.79798797, 0.20201203],
       [0.84352017, 0.15647983],
       [0.70556143, 0.29443857],
       [0.73896869, 0.26103131],
       [0.34610251, 0.65389749],
       [0.88623492, 0.11376508],
       [0.39848078, 0.60151922],
       [0.93568401, 0.06431599],
       [0.90878549, 0.09121451],
       [0.71629328, 0.28370672],
       [0.85713438, 0.14286562],
       [0.91109248, 0.08890752],
       [0.88599789, 0.11400211],
       [0.4757004 , 0.5242996 ],
       [0.64284154, 0.35715846],
       [0.47528131, 0.52471869],
       [0.913107  , 0.086893  ],
       [0.84979464, 0.15020536],
       [0.90976355, 0.09023645],
       [0.81083205, 0.18916795],
       [0.21807156, 0.78192844],
       [0.53874953, 0.46125047],
       [0.90486611, 0.09513389],
       [0.84115814, 0.15884186],
       [0.24041592, 0.75958408],
       [0.87257504, 0.12742496],
       [0.78041871, 0.21958129],
       [0.8756756 , 0.1243244 ],
       [0.74607963, 0.25392037],
       [0.88403046, 0.11596954],
       [0.90954276, 0.09045724],
       [0.13828343, 0.86171657],
       [0.51432963, 0.48567037],
       [0.193482  , 0.806518  ],
       [0.88699993, 0.11300007],
       [0.69016365, 0.30983635],
       [0.77003253, 0.22996747],
       [0.27798376, 0.72201624],
       [0.78996963, 0.21003037],
       [0.8165942 , 0.1834058 ],
       [0.80339327, 0.19660673],
       [0.86561924, 0.13438076],
       [0.81870338, 0.18129662],
       [0.15112812, 0.84887188],
       [0.23875409, 0.76124591],
       [0.29578524, 0.70421476],
       [0.80204683, 0.19795317],
       [0.87044054, 0.12955946],
       [0.85248426, 0.14751574],
       [0.40534496, 0.59465504],
       [0.74719662, 0.25280338],
       [0.43792713, 0.56207287],
       [0.79709685, 0.20290315],
       [0.77355081, 0.22644919],
       [0.23129147, 0.76870853],
       [0.47891805, 0.52108195],
       [0.82874256, 0.17125744],
       [0.74906708, 0.25093292],
       [0.85584683, 0.14415317],
       [0.81831034, 0.18168966],
       [0.18179677, 0.81820323],
       [0.28362986, 0.71637014],
       [0.78569432, 0.21430568],
       [0.85044162, 0.14955838],
       [0.80822112, 0.19177888],
       [0.78819214, 0.21180786],
       [0.85504434, 0.14495566],
       [0.90787565, 0.09212435],
       [0.7268115 , 0.2731885 ],
       [0.69850985, 0.30149015],
       [0.70690565, 0.29309435],
       [0.88104366, 0.11895634],
       [0.92908881, 0.07091119],
       [0.88884087, 0.11115913],
       [0.8107472 , 0.1892528 ],
       [0.88933684, 0.11066316],
       [0.50045701, 0.49954299],
       [0.87285278, 0.12714722],
       [0.89523574, 0.10476426],
       [0.91457259, 0.08542741],
       [0.82287925, 0.17712075],
       [0.27698444, 0.72301556],
       [0.42992407, 0.57007593],
       [0.87331782, 0.12668218],
       [0.43780517, 0.56219483],
       [0.83384143, 0.16615857],
       [0.86024302, 0.13975698],
       [0.47030182, 0.52969818],
       [0.5019227 , 0.4980773 ],
       [0.75285823, 0.24714177],
       [0.85035929, 0.14964071],
       [0.80508756, 0.19491244],
       [0.78464969, 0.21535031],
       [0.7896984 , 0.2103016 ],
       [0.91088136, 0.08911864],
       [0.75902333, 0.24097667],
       [0.81828509, 0.18171491],
       [0.46609779, 0.53390221],
       [0.07974319, 0.92025681],
       [0.80111865, 0.19888135],
       [0.8231549 , 0.1768451 ],
       [0.82635268, 0.17364732],
       [0.62937265, 0.37062735],
       [0.8388725 , 0.1611275 ],
       [0.87189015, 0.12810985],
       [0.91579023, 0.08420977],
       [0.92637499, 0.07362501],
       [0.89630431, 0.10369569],
       [0.701052  , 0.298948  ],
       [0.8240993 , 0.1759007 ],
       [0.82549026, 0.17450974],
       [0.7486147 , 0.2513853 ],
       [0.76978871, 0.23021129],
       [0.66533836, 0.33466164],
       [0.88721173, 0.11278827],
       [0.91465442, 0.08534558],
       [0.27027472, 0.72972528],
       [0.80998767, 0.19001233],
       [0.21650629, 0.78349371],
       [0.0501193 , 0.9498807 ],
       [0.7607292 , 0.2392708 ],
       [0.18730665, 0.81269335],
       [0.81838646, 0.18161354],
       [0.75499695, 0.24500305],
       [0.8524715 , 0.1475285 ],
       [0.84198484, 0.15801516],
       [0.19992152, 0.80007848],
       [0.14269105, 0.85730895],
       [0.87776065, 0.12223935],
       [0.86477948, 0.13522052],
       [0.89702972, 0.10297028],
       [0.73160029, 0.26839971],
       [0.92331912, 0.07668088],
       [0.83168602, 0.16831398],
       [0.78220721, 0.21779279],
       [0.82448779, 0.17551221],
       [0.83666777, 0.16333223],
       [0.45489798, 0.54510202],
       [0.36714144, 0.63285856],
       [0.88505785, 0.11494215],
       [0.90103286, 0.09896714],
       [0.58358522, 0.41641478],
       [0.88206493, 0.11793507],
       [0.40779438, 0.59220562],
       [0.8598584 , 0.1401416 ],
       [0.27460131, 0.72539869],
       [0.91961578, 0.08038422],
       [0.89817524, 0.10182476],
       [0.19487612, 0.80512388],
       [0.38169976, 0.61830024],
       [0.81686445, 0.18313555],
       [0.82945938, 0.17054062],
       [0.39673305, 0.60326695],
       [0.31020264, 0.68979736],
       [0.53618379, 0.46381621],
       [0.78619833, 0.21380167],
       [0.08420776, 0.91579224],
       [0.88816855, 0.11183145],
       [0.84279113, 0.15720887],
       [0.7610864 , 0.2389136 ],
       [0.82406476, 0.17593524],
       [0.35467155, 0.64532845],
       [0.63123361, 0.36876639],
       [0.3955857 , 0.6044143 ]])

In [23]:
df['text'][0]

'head conservative republican faction u.s. congress voted month huge expansion national debt pay tax cuts called fiscal conservative sunday urged budget restraint keeping sharp pivot way among republicans u.s. representative mark meadows speaking cbs face nation drew hard line federal spending lawmakers bracing battle january return holidays wednesday lawmakers begin trying pass federal budget fight likely linked issues immigration policy even november congressional election campaigns approach republicans seek keep control congress president donald trump republicans want big budget increase military spending democrats also want proportional increases non-defense discretionary spending programs support education scientific research infrastructure public health environmental protection trump administration already willing say going increase non-defense discretionary spending ... percent meadows chairman small influential house freedom caucus said program democrats saying thats enough need give government pay raise percent fiscal conservative dont see rationale ... eventually run peoples money said meadows among republicans voted late december partys debt-financed tax overhaul expected balloon federal budget deficit add trillion years trillion national debt interesting hear mark talk fiscal responsibility democratic u.s. representative joseph crowley said cbs crowley said republican tax bill would require theunited states borrow trillion paid future generations finance tax cuts corporations rich one least ... fiscally responsible bills weve ever seen passed history house representatives think going paying many many years come crowley said republicans insist tax package biggest u.s. tax overhaul years boost economy job growth house speaker paul ryan also supported tax bill recently went meadows making clear radio interview welfare entitlement reform party often calls would top republican priority republican parlance entitlement programs mean food stamps housing assistance medicare medicaid health insurance elderly poor disabled well programs created washington assist needy democrats seized ryans early december remarks saying showed republicans would try pay tax overhaul seeking spending cuts social programs goals house republicans may take back seat senate votes democrats needed approve budget prevent government shutdown democrats use leverage senate republicans narrowly control defend discretionary non-defense programs social spending tackling issue dreamers people brought illegally country children trump september put march expiration date deferred action childhood arrivals daca program protects young immigrants deportation provides work permits president said recent twitter messages wants funding proposed mexican border wall immigration law changes exchange agreeing help dreamers representative debbie dingell told cbs favor linking issue policy objectives wall funding need daca clean said.on wednesday trump aides meet congressional leaders discuss issues followed weekend strategy sessions trump republican leaders jan. white house said trump also scheduled meet sunday florida republican governor rick scott wants emergency aid house passed billion aid package hurricanes florida texas puerto rico wildfires california package far exceeded billion requested trump administration senate yet voted aid'